name: Build and Push to GHCR

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

on:
  push:
    branches: ["main"]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (excluding Go)
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libseccomp-dev \
            pkg-config \
            squashfs-tools \
            cryptsetup \
            wget \
            git \
            uuid-dev \
            libgpgme-dev \
            libglib2.0-dev \
            libselinux1-dev \
            libzstd-dev \
            python3-pip

      - name: Install Go
        run: |
          wget https://go.dev/dl/go1.21.4.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build and Install Apptainer
        run: |
          export PATH="/usr/local/go/bin:$PATH"
          rm -rf apptainer
          git clone https://github.com/apptainer/apptainer.git
          cd apptainer
          git checkout v1.3.0
          ./mconfig
          make -C builddir
          sudo make -C builddir install
          echo "/usr/local/bin" >> $GITHUB_PATH
          apptainer version


      - name: Build SIF Image
        run: |
          export PATH="/usr/local/bin:/usr/local/go/bin:$PATH"
          apptainer build dataleak.sif apptainer/dataleak.def

      - name: Login to GHCR
        run: |
          export PATH="/usr/local/bin:$PATH"
          echo "${{ secrets.GHCR_TOKEN }}" | apptainer remote login \
            --username "${{ github.repository_owner }}" \
            --password-stdin ghcr.io

      - name: Push to GHCR
        run: |
          export PATH="/usr/local/bin:$PATH"
          apptainer push dataleak.sif oras://ghcr.io/${{ github.repository_owner }}/dataleak:latest

      - name: Push to Sylabs (optional)
        run: |
          export PATH="/usr/local/bin:$PATH"
          apptainer push dataleak.sif library://vincent9339/project/dataleak:latest
