name: Build and Push to GHCR

on:
  push:
    branches: ["main"]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build Container
        run: |
          cd apptainer
          apptainer build ../dataleak.sif dataleak.def

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: |
          # Push with ORAS
          apptainer push dataleak.sif oras://ghcr.io/${{github.repository_owner}}/dataleak:latest

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            apptainer push dataleak.sif oras://ghcr.io/${{github.repository_owner}}/dataleak:$TAG
          fi
