name: Build and Push to GHCR
env:
  GHCR_TOKEN: ${{secrets.GHCR_TOKEN}} 
on:
  push:
    branches: ["main"]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build Container
        run: |
          cd apptainer
          apptainer build --sandbox ../dataleak.sif dataleak.def

      - name: Login to GHCR  
        run: |  
          echo "${{secrets.GHCR_TOKEN}}" | apptainer remote login --username ${{ github.repository_owner }} --password-stdin ghcr.io  
      
      - name: Push to GHCR  
        run: |  
          apptainer push dataleak.sif oras://ghcr.io/${{ github.repository_owner }}/dataleak:latest  

      - name: Push to Sylabs (Optional)  
        run: |  
          apptainer push dataleak.sif library://vincent9339/project/dataleak:latest  
